services:
  - type: web
    name: docu-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: docu-ai-frontend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/App.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BACKEND_URL
        value: https://docu-ai-backend.onrender.com
